-- Add migration script here
CREATE TABLE IF NOT EXISTS Batch (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       reference VARCHAR NOT NULL UNIQUE,
       sku VARCHAR NOT NULL REFERENCES Product (sku),
       purchased_quantity INTEGER NOT NULL,
       eta TIMESTAMP WITH TIME ZONE NOT NULL
);
