-- Add migration script here
CREATE TABLE IF NOT EXISTS OrderLine (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       sku VARCHAR NOT NULL,
       qty INTEGER NOT NULL,
       order_id VARCHAR NOT NULL
);
