-- Add migration script here
CREATE TABLE IF NOT EXISTS Allocations (
       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       order_line_id INTEGER NOT NULL REFERENCES OrderLine (id),
       batch_id INTEGER NOT NULL REFERENCES Batch (id)
);
